package btl_nhom3;

import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Vector;
import java.util.logging.Level;
import javax.swing.table.DefaultTableModel;

public class BaoCaoThongKe extends javax.swing.JFrame {

    String sql = "SELECT * FROM `hoa_don` ORDER BY `MaHD` DESC";
    connectDB conn = new connectDB();
    public BaoCaoThongKe() {
        initComponents();
        show(sql);//them bang thanh cong
        
    }
    ArrayList<Integer> nam = new ArrayList<>();
    ArrayList<Integer> thang = new ArrayList<>();
    ArrayList<Integer> soNuoc = new ArrayList<>();

    public void show(String sql) {
        try {
            String[] arry = {"Năm","Tháng","Số nước"};
            DefaultTableModel model = new DefaultTableModel(arry, 0);
            ResultSet rs = conn.stmt.executeQuery(sql);
            
            while (rs.next()) {
                Vector vector = new Vector();
                Date cl = new Date(2020,1,1);
                cl = rs.getDate("NgayLap");
                int nam_ = 1900 + cl.getYear();
                int thang_ = 1 + cl.getMonth();
                int soNuoc_ = rs.getInt("ChiSoMoi") - rs.getInt("ChiSoCu");
                nam.add(nam_);
                thang.add(thang_);
                soNuoc.add(soNuoc_);
            }
            // sap xep danh sach theo nam, thang
            sort();
            for(int i=0;i<nam.size()-1;i++){
                int j = i+1;
                if (nam.get(i) - nam.get(j) == 0 && thang.get(i) - thang.get(j) == 0){// cùng năm
                    soNuoc.set(i, soNuoc.get(i)+soNuoc.get(j));
                    nam.remove(j);
                    thang.remove(j);
                    soNuoc.remove(j);
                    i--;
                }
            }
           for(int i=0;i<nam.size();i++){
               model.addRow(new Object[]{
                   nam.get(i), thang.get(i), soNuoc.get(i)
               });
           }
            tableThongKe.setModel(model);
        } catch (Exception e) {
            System.out.println("Kết nối thất bại");
        }
    }
    void sort(){//sap xep theo nam (tang dan)
        for(int i=0;i<nam.size()-1;i++){//sap xep nam tang dan
            for(int j=i+1;j<nam.size();j++){
                if (nam.get(i) - nam.get(j) > 0){
                    int temp = nam.get(i);
                    nam.set(i, nam.get(j));
                    nam.set(j, temp);
                    
                    temp = thang.get(i);
                    thang.set(i, thang.get(j));
                    thang.set(j, temp);
                    
                    temp = soNuoc.get(i);
                    soNuoc.set(i, soNuoc.get(j));
                    soNuoc.set(j, temp);
                }
            }
        }
        for(int i=0;i<nam.size()-1;i++){
            for(int j=i+1;j<nam.size();j++){
                if (nam.get(i) - nam.get(j) == 0){//cung nam
                    if(thang.get(i)-thang.get(j)>0){
                        int temp = nam.get(i);
                    nam.set(i, nam.get(j));
                    nam.set(j, temp);
                    
                    temp = thang.get(i);
                    thang.set(i, thang.get(j));
                    thang.set(j, temp);
                    
                    temp = soNuoc.get(i);
                    soNuoc.set(i, soNuoc.get(j));
                    soNuoc.set(j, temp);
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnquaylai = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableThongKe = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Báo cáo tiêu thụ nước");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Bảng thống kê tiêu thụ nước theo tháng");

        btnquaylai.setText("Quay lại");
        btnquaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquaylaiActionPerformed(evt);
            }
        });

        tableThongKe.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tableThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableThongKe.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableThongKe.setRowHeight(25);
        jScrollPane1.setViewportView(tableThongKe);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel1)
                        .addGap(0, 228, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnquaylai)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnquaylai)
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnquaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquaylaiActionPerformed
        dispose();
        Main a = new Main();
        a.setVisible(true);
    }//GEN-LAST:event_btnquaylaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaoCaoThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaoCaoThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaoCaoThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaoCaoThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaoCaoThongKe().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnquaylai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableThongKe;
    // End of variables declaration//GEN-END:variables
}
